name: Integration testing

on:
  workflow_dispatch:
  push:
    branches-ignore:
      ["main"]
  pull_request:
    branches:
      ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  integration:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      rabbitmq:
        image: rabbitmq:3.11
        ports:
          - 5672:5672

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Create directory for provider`s files
      id: provider_path
      run: |
        mkdir provider
        echo "provider_path=$(realpath ./provider/)" >> $GITHUB_OUTPUT
    - name: Download Cooplan Definition Provider
      uses: dsaltares/fetch-gh-release-asset@1.1.0
      with:
        repo: 'simple0x47/cooplan-definition-provider'
        file: 'cooplan-definition-provider'
        token: ${{ secrets.GITHUB_TOKEN }}
        target: ${{ format('{0}/cooplan-definition-provider', steps.provider_path.outputs.provider_path) }}
    - name: Download provider`s api.json
      uses: dsaltares/fetch-gh-release-asset@1.1.0
      with:
        repo: 'simple0x47/cooplan-definition-provider'
        file: 'api.json'
        target: ${{ format('{0}/api.json', steps.provider_path.outputs.provider_path) }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Download provider`s config.json
      uses: dsaltares/fetch-gh-release-asset@1.1.0
      with:
        repo: 'simple0x47/cooplan-definition-provider'
        file: 'config.json'
        token: ${{ secrets.GITHUB_TOKEN }}
        target: ${{ format('{0}/config.json', steps.provider_path.outputs.provider_path) }}
    - name: Wait for RabbitMQ to become alive
      run: |
        sleep 15
    - name: Run Cooplan Definition Provider
      run: |
        cd provider
        chmod +x cooplan-definition-provider
        ./cooplan-definition-provider api.json config.json &
        cd ../
      env:
        GIT_USERNAME: 'simple0x47'
        GIT_PASSWORD: ${{ secrets.DEFINITIONS_ACCESS_TOKEN }}
    - name: Run tests
      run: cargo test --verbose
      env:
        API_CONSUMER_FILE: ./api_consumer.json
        CONSUMER_CONFIG_FILE: ./config.json
        IDENTITY_CLIENT_AUDIENCE: ${{ secrets.IDENTITY_CLIENT_AUDIENCE }}
        IDENTITY_CLIENT_ID: ${{ secrets.IDENTITY_CLIENT_ID }}
        IDENTITY_CLIENT_SECRET: ${{ secrets.IDENTITY_CLIENT_SECRET }}
        IDENTITY_PROVIDER_URL: ${{ secrets.IDENTITY_PROVIDER_URL }}
